/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Completar el siguiente código en Visual C++ de tal forma que, al leer el valor de un artículo en pesos
colombianos, permita calcular y escribir el valor de su equivalencia en dólares y euros1
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;
  }