/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:

NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
float _P1,N1,P2,N2.P3,N3,DEFINITIVA;
cout << ” Digite tres notas”;
P1=N1*0.25;
P2=N2*0.35;
P3=N3*0.40;
Def =  P1+P2+P3;		
cout << “la definitiva es:”<<DEFINITIVA<<endl;
system (“pause”);
}
  return 0;
