/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Elaborar un programa en Visual C++, que calcule en pesos, el costo total semanal de la producción de una
empresa, El programa debe permitir ingresar el número de unidades producidas a la semana y el actual valor
del dólar (TRM).
Se debe tener en cuenta que los costos fijos son de 285 dólares y el costo de producir cada unidad es de 2.5
dólares, así:
Costo Total = Costos Fijos + Número de unidades * Costo unitario
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;
  }