/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
El Concesionario MAXAUTOS necesita un programa en Visual C++ que calcule y escriba el valor del impuesto a
pagar por un vehículo, sabiendo que corresponde al 2.5% de su valor comercial
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;