/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Juan desea vender un lote rectangular y para ello se debe crear un programa en Visual C++ que permita calcular
y escribir el valor de este, sabiendo que el valor de cada metro cuadrado es de $200.000, el valor del ancho es
dado por el usuario y el largo es el doble del ancho
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;
  }