/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Realizar un programa en Visual C++, que calcule y escriba la superficie total de un cilindro recto:
Área del Cilindro: 𝑆 = 2𝜋𝑟ℎ + 2𝜋𝑟2
Declarar como constante = 3.14159265
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;