/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
El Supermercado EL PODER requiere un programa en Visual C++, que lea el precio unitario y la cantidad de
artículos y calcule el valor a pagar por la compra, sabiendo que el IVA es del 19% del valor total. Escribir el precio
unitario, la cantidad, el valor total, el valor del IVA y el valor neto a pagar.
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;