/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Realizar un programa en Visual C++ que imprima la suma de los dígitos de un número digitado por teclado,
entre 10 y 99. Por ejemplo, si el número es 24 debe imprimir el valor de la suma de los dígitos (2 + 4 = 6)
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;