/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Elaborar un programa en Visual C++, para una empresa de acueducto que requiere determinar el pago que
debe realizar una persona por el total de metros cúbicos de agua consumidos al llenar un estanque de forma
rectangular y cuyas dimensiones de largo, ancho y profundidad se ingresan por teclado. El costo por metro
cúbico es de $1.250.
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;