/*T07E01::ESCRIBIR UN PROGRAMA EN VISUAL C++, QUE DESPLIEGUE LOS RESULTADOS 
DE SIGUIENTES EXPRESIONES:
Crear un programa en Visual C++ que permita calcular y escribir la velocidad promedio de un vehículo, dada la
distancia recorrida en kilómetros y el tiempo en horas.
NOMBRE: JULIAN DAVID RUIZ PARDO, VALENTINA MONTAÑA, SANTIAGO VARGAS 
ASIGNATURA:PROGRAMACION l*/
#include <iostream>
  using namespace std;
int
main ()
{
  return 0;
  }